/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analysis/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare */
        post: operations["compare_api_analysis_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gaps */
        post: operations["gaps_api_analysis_gaps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comparisons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Saved Comparisons */
        get: operations["list_saved_comparisons_api_comparisons_get"];
        put?: never;
        /** Save Comparison */
        post: operations["save_comparison_api_comparisons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comparisons/{comparison_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Comparison */
        delete: operations["delete_comparison_api_comparisons__comparison_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exports/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Papers */
        get: operations["export_papers_api_exports_papers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ingestion Job */
        get: operations["get_ingestion_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Llm Status */
        get: operations["llm_status_api_llm_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notes */
        get: operations["list_notes_api_notes_get"];
        put?: never;
        /** Create Note */
        post: operations["create_note_api_notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes/{note_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Note */
        delete: operations["delete_note_api_notes__note_id__delete"];
        options?: never;
        head?: never;
        /** Update Note */
        patch: operations["update_note_api_notes__note_id__patch"];
        trace?: never;
    };
    "/api/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Papers */
        get: operations["list_papers_api_papers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/external": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add External Paper */
        post: operations["add_external_paper_api_papers_external_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Papers */
        post: operations["upload_papers_api_papers_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Paper Detail */
        get: operations["get_paper_detail_api_papers__paper_id__get"];
        put?: never;
        post?: never;
        /** Delete Paper */
        delete: operations["delete_paper_api_papers__paper_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Paper Assets */
        get: operations["get_paper_assets_api_papers__paper_id__assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/assets/{element_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Figure Asset */
        get: operations["get_figure_asset_api_papers__paper_id__assets__element_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/chunks/{chunk_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Paper Chunk */
        get: operations["get_paper_chunk_api_papers__paper_id__chunks__chunk_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Paper File */
        get: operations["get_paper_file_api_papers__paper_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/pages/{page}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Paper Page */
        get: operations["get_paper_page_api_papers__paper_id__pages__page__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paper Tags */
        get: operations["paper_tags_api_papers__paper_id__tags_get"];
        /** Set Paper Tags */
        put: operations["set_paper_tags_api_papers__paper_id__tags_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Research Conversations */
        get: operations["list_research_conversations_api_research_conversations_get"];
        put?: never;
        /** Create Research Conversation */
        post: operations["create_research_conversation_api_research_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Research Conversation */
        get: operations["get_research_conversation_api_research_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/conversations/{conversation_id}/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Research Memory Page */
        get: operations["get_research_memory_page_api_research_conversations__conversation_id__memory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Research Messages Page */
        get: operations["get_research_messages_page_api_research_conversations__conversation_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer */
        post: operations["answer_api_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search History */
        get: operations["search_history_api_search_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/history/{history_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete History */
        delete: operations["delete_history_api_search_history__history_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer Stream */
        post: operations["answer_stream_api_search_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tags */
        get: operations["list_tags_api_tags_get"];
        put?: never;
        /** Create Tag */
        post: operations["create_tag_api_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Tag */
        put: operations["update_tag_api_tags__tag_id__put"];
        post?: never;
        /** Delete Tag */
        delete: operations["delete_tag_api_tags__tag_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workspaces */
        get: operations["list_workspaces_api_workspaces_get"];
        put?: never;
        /** Create Workspace */
        post: operations["create_workspace_api_workspaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Workspace
         * @description Resolve a switch target without exposing inaccessible workspaces.
         */
        get: operations["get_workspace_api_workspaces__workspace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename Workspace */
        patch: operations["rename_workspace_api_workspaces__workspace_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisRequest */
        AnalysisRequest: {
            /** Paper Ids */
            paper_ids: string[];
            /** User Id */
            user_id?: string | null;
        };
        /** AnswerClaim */
        AnswerClaim: {
            /** Citation Ids */
            citation_ids?: number[];
            /** Claim Id */
            claim_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "paper" | "general" | "hypothesis";
            /** Text */
            text: string;
        };
        /** Body_upload_papers_api_papers_upload_post */
        Body_upload_papers_api_papers_upload_post: {
            /** Files */
            files: string[];
            /** User Id */
            user_id?: string | null;
        };
        /** Chunk */
        Chunk: {
            /** Id */
            id?: string;
            /** Page */
            page: number;
            /** Paper Id */
            paper_id: string;
            /**
             * Section
             * @default 本文
             */
            section: string;
            /** Text */
            text: string;
        };
        /** Citation */
        Citation: {
            /** Chunk Id */
            chunk_id: string;
            /** Excerpt */
            excerpt: string;
            /** Index */
            index: number;
            /** Page */
            page: number;
            /** Paper Id */
            paper_id: string;
            /** Paper Title */
            paper_title: string;
            /** Score */
            score: number;
            /** Section */
            section: string;
        };
        /** ComparisonRow */
        ComparisonRow: {
            /** Limitations */
            limitations: string;
            /** Method */
            method: string;
            /** Paper Id */
            paper_id: string;
            /** Purpose */
            purpose: string;
            /** Results */
            results: string;
            /** Title */
            title: string;
        };
        /** DocumentElement */
        DocumentElement: {
            /** Asset Key */
            asset_key?: string | null;
            /** Bbox */
            bbox?: number[] | null;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "text" | "table" | "figure" | "caption";
            /** Page */
            page: number;
            /** Paper Id */
            paper_id: string;
            /** Structured Data */
            structured_data?: {
                [key: string]: unknown;
            } | unknown[] | null;
            /**
             * Text
             * @default
             */
            text: string;
        };
        /** ExternalPaperRequest */
        ExternalPaperRequest: {
            /**
             * Abstract
             * @default
             */
            abstract: string;
            /** Authors */
            authors?: string[];
            /** Identifier */
            identifier: string;
            /** Title */
            title?: string | null;
            /** User Id */
            user_id?: string | null;
            /** Year */
            year?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestionJob */
        IngestionJob: {
            /** Attempts */
            attempts: number;
            /** Created At */
            created_at: string;
            /** Error Message */
            error_message?: string | null;
            /** Id */
            id: string;
            /** Paper Id */
            paper_id: string;
            /** Progress */
            progress: number;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed";
            /** Updated At */
            updated_at: string;
        };
        /** LLMStatus */
        LLMStatus: {
            /** Agentic Dependencies Available */
            agentic_dependencies_available: boolean;
            /** Configured */
            configured: boolean;
            /** Embedding Model */
            embedding_model: string;
            /** Last Failure Code */
            last_failure_code?: ("api_key_missing" | "dependency_missing" | "no_evidence" | "grounding_failed" | "authentication_failed" | "permission_denied" | "model_not_found" | "rate_limited" | "api_timeout" | "network_error" | "model_api_error" | "deadline_exceeded" | "model_timeout" | "model_unavailable" | "provider_unavailable" | "model_call_failed" | "generation_failed" | "citation_validation_failed" | "grounding_audit_failed" | "repair_failed" | "structured_output_invalid" | "verification_skipped_timeout") | null;
            /** Model */
            model: string;
        };
        /** MeResponse */
        MeResponse: {
            personal_workspace: components["schemas"]["Workspace"];
            user: components["schemas"]["User"];
        };
        /** Note */
        Note: {
            /** Author Id */
            author_id: string;
            /** Content */
            content: string;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Paper Id */
            paper_id: string | null;
            /** Title */
            title: string;
            /** Updated At */
            updated_at: string;
        };
        /** NoteCreate */
        NoteCreate: {
            /** Content */
            content: string;
            /** Paper Id */
            paper_id?: string | null;
            /** Title */
            title: string;
        };
        /** NoteUpdate */
        NoteUpdate: {
            /** Content */
            content?: string | null;
            /** Title */
            title?: string | null;
        };
        /** PaperDetail */
        PaperDetail: {
            /** Abstract */
            abstract: string;
            /** Authors */
            authors: string[];
            /** Byte Size */
            byte_size?: number | null;
            /** Chunk Count */
            chunk_count: number;
            /** Created At */
            created_at: string;
            /** Error Message */
            error_message?: string | null;
            /** External Id */
            external_id: string | null;
            /** Id */
            id: string;
            /** Mime Type */
            mime_type?: string | null;
            /** Page Count */
            page_count: number;
            /** Source */
            source: string;
            /** Status */
            status: string;
            /** Storage Key */
            storage_key?: string | null;
            /** Title */
            title: string;
            /** Year */
            year: number | null;
        };
        /** PaperPage */
        PaperPage: {
            /** Chunks */
            chunks: components["schemas"]["Chunk"][];
            /** Elements */
            elements?: components["schemas"]["DocumentElement"][];
            /** Page */
            page: number;
            /** Paper Id */
            paper_id: string;
            /**
             * Quality
             * @default 0
             */
            quality: number;
            /**
             * Text
             * @default
             */
            text: string;
            /**
             * Text Source
             * @default none
             * @enum {string}
             */
            text_source: "native" | "ocr" | "none";
        };
        /** PaperSummary */
        PaperSummary: {
            /** Abstract */
            abstract: string;
            /** Authors */
            authors: string[];
            /** Chunk Count */
            chunk_count: number;
            /** Created At */
            created_at: string;
            /** Error Message */
            error_message?: string | null;
            /** External Id */
            external_id: string | null;
            /** Id */
            id: string;
            /** Page Count */
            page_count: number;
            /** Source */
            source: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Year */
            year: number | null;
        };
        /** PaperTagsUpdate */
        PaperTagsUpdate: {
            /** Tag Ids */
            tag_ids?: string[];
        };
        /** ResearchConversation */
        ResearchConversation: {
            /** Created At */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Id */
            id: string;
            /**
             * Memory Event Count
             * @default 0
             */
            memory_event_count: number;
            /**
             * Message Count
             * @default 0
             */
            message_count: number;
            /** Summary */
            summary: string;
            /** Title */
            title: string;
            /** Updated At */
            updated_at: string;
        };
        /** ResearchConversationCreate */
        ResearchConversationCreate: {
            /**
             * Title
             * @default 新しい研究対話
             */
            title: string;
        };
        /** ResearchConversationDetail */
        ResearchConversationDetail: {
            /** Created At */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Id */
            id: string;
            /**
             * Memory Event Count
             * @default 0
             */
            memory_event_count: number;
            /**
             * Message Count
             * @default 0
             */
            message_count: number;
            /** Messages */
            messages?: components["schemas"]["ResearchMessage"][];
            /** Summary */
            summary: string;
            /** Title */
            title: string;
            /** Updated At */
            updated_at: string;
        };
        /** ResearchGap */
        ResearchGap: {
            /** Gap */
            gap: string;
            /** Opportunity */
            opportunity: string;
            /** Page */
            page: string;
            /** Paper Id */
            paper_id: string;
            /** Paper Title */
            paper_title: string;
        };
        /** ResearchMemoryEvent */
        ResearchMemoryEvent: {
            /** Content */
            content: string;
            /** Conversation Id */
            conversation_id: string;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "hypothesis" | "assumption" | "unresolved_question" | "planned_test";
            /** Ordinal */
            ordinal: number;
            /** Source Message Id */
            source_message_id?: string | null;
        };
        /** ResearchMemoryPage */
        ResearchMemoryPage: {
            /** Items */
            items?: components["schemas"]["ResearchMemoryEvent"][];
            /** Next Before Ordinal */
            next_before_ordinal?: number | null;
        };
        /** ResearchMessage */
        ResearchMessage: {
            /** Citations */
            citations?: components["schemas"]["Citation"][];
            /** Content */
            content: string;
            /** Conversation Id */
            conversation_id: string;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Ordinal */
            ordinal: number;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
        };
        /** ResearchMessagePage */
        ResearchMessagePage: {
            /** Items */
            items?: components["schemas"]["ResearchMessage"][];
            /** Next Before Ordinal */
            next_before_ordinal?: number | null;
        };
        /** SavedComparison */
        SavedComparison: {
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Paper Ids */
            paper_ids: string[];
            /** Result */
            result: {
                [key: string]: unknown;
            }[];
            /** User Id */
            user_id: string;
        };
        /** SavedComparisonCreate */
        SavedComparisonCreate: {
            /** Name */
            name: string;
            /** Paper Ids */
            paper_ids: string[];
        };
        /** SearchHistory */
        SearchHistory: {
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Paper Ids */
            paper_ids: string[];
            /** Query */
            query: string;
            /** Result Summary */
            result_summary: {
                [key: string]: unknown;
            };
            /** User Id */
            user_id: string;
        };
        /** SearchRequest */
        SearchRequest: {
            /** Conversation Id */
            conversation_id?: string | null;
            /**
             * Limit
             * @default 8
             */
            limit: number;
            /** Paper Ids */
            paper_ids?: string[];
            /** Query */
            query: string;
            /** User Id */
            user_id?: string | null;
            /** Year From */
            year_from?: number | null;
            /** Year To */
            year_to?: number | null;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Answer */
            answer: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Claims */
            claims?: components["schemas"]["AnswerClaim"][];
            /** Conversation Id */
            conversation_id?: string | null;
            /** Fallback Reason */
            fallback_reason?: ("api_key_missing" | "dependency_missing" | "no_evidence" | "grounding_failed" | "authentication_failed" | "permission_denied" | "model_not_found" | "rate_limited" | "api_timeout" | "network_error" | "model_api_error" | "deadline_exceeded" | "model_timeout" | "model_unavailable" | "provider_unavailable" | "model_call_failed" | "generation_failed" | "citation_validation_failed" | "grounding_audit_failed" | "repair_failed" | "structured_output_invalid" | "verification_skipped_timeout") | null;
            /**
             * Generation Mode
             * @default local_fallback
             * @enum {string}
             */
            generation_mode: "agentic_rag" | "local_fallback";
            /**
             * Grounded
             * @default false
             */
            grounded: boolean;
            /**
             * Grounding Status
             * @default not_checked
             * @enum {string}
             */
            grounding_status: "verified" | "rejected" | "not_checked" | "no_evidence";
            /**
             * Llm Attempted
             * @default false
             */
            llm_attempted: boolean;
            /**
             * Llm Succeeded
             * @default false
             */
            llm_succeeded: boolean;
            /** Memory Delta */
            memory_delta?: {
                [key: string]: unknown;
            };
            /** Model */
            model?: string | null;
            /**
             * Model Calls
             * @default 0
             */
            model_calls: number;
            /** Retrieval Queries */
            retrieval_queries?: string[];
        };
        /** Tag */
        Tag: {
            /**
             * Color
             * @default #64748b
             */
            color: string;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** TagCreate */
        TagCreate: {
            /**
             * Color
             * @default #64748b
             */
            color: string;
            /** Name */
            name: string;
        };
        /** UploadResult */
        UploadResult: {
            /**
             * Duplicate
             * @default false
             */
            duplicate: boolean;
            /** Error */
            error?: string | null;
            /** Filename */
            filename: string;
            job?: components["schemas"]["IngestionJob"] | null;
            paper?: components["schemas"]["PaperSummary"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "processing" | "ready" | "failed" | "duplicate" | "rejected";
            /** Success */
            success: boolean;
        };
        /** User */
        User: {
            /** Created At */
            created_at: string;
            /** Display Name */
            display_name?: string | null;
            /** Email */
            email?: string | null;
            /** Id */
            id: string;
            /** Issuer */
            issuer: string;
            /** Subject */
            subject: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Workspace */
        Workspace: {
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Is Personal */
            is_personal: boolean;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "editor" | "viewer";
        };
        /** WorkspaceCreate */
        WorkspaceCreate: {
            /** Name */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    compare_api_analysis_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gaps_api_analysis_gaps_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchGap"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_saved_comparisons_api_comparisons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedComparison"][];
                };
            };
        };
    };
    save_comparison_api_comparisons_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedComparisonCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedComparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_comparison_api_comparisons__comparison_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comparison_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_papers_api_exports_papers_get: {
        parameters: {
            query: {
                format: string;
                paper_ids?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_ingestion_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    llm_status_api_llm_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMStatus"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    list_notes_api_notes_get: {
        parameters: {
            query?: {
                paper_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_note_api_notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_note_api_notes__note_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_note_api_notes__note_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_papers_api_papers_get: {
        parameters: {
            query?: {
                /** @deprecated */
                user_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_external_paper_api_papers_external_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExternalPaperRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_papers_api_papers_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_papers_api_papers_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_paper_detail_api_papers__paper_id__get: {
        parameters: {
            query?: {
                /** @deprecated */
                user_id?: string | null;
            };
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_paper_api_papers__paper_id__delete: {
        parameters: {
            query?: {
                /** @deprecated */
                user_id?: string | null;
            };
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_paper_assets_api_papers__paper_id__assets_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentElement"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_figure_asset_api_papers__paper_id__assets__element_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
                element_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_paper_chunk_api_papers__paper_id__chunks__chunk_id__get: {
        parameters: {
            query?: {
                /** @deprecated */
                user_id?: string | null;
            };
            header?: never;
            path: {
                paper_id: string;
                chunk_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chunk"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_paper_file_api_papers__paper_id__file_get: {
        parameters: {
            query?: {
                /** @deprecated */
                user_id?: string | null;
            };
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_paper_page_api_papers__paper_id__pages__page__get: {
        parameters: {
            query?: {
                /** @deprecated */
                user_id?: string | null;
            };
            header?: never;
            path: {
                paper_id: string;
                page: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    paper_tags_api_papers__paper_id__tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_paper_tags_api_papers__paper_id__tags_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaperTagsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_research_conversations_api_research_conversations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchConversation"][];
                };
            };
        };
    };
    create_research_conversation_api_research_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchConversationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchConversation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_research_conversation_api_research_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchConversationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_research_memory_page_api_research_conversations__conversation_id__memory_get: {
        parameters: {
            query?: {
                kind?: ("hypothesis" | "assumption" | "unresolved_question" | "planned_test") | null;
                limit?: number;
                before_ordinal?: number | null;
            };
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchMemoryPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_research_messages_page_api_research_conversations__conversation_id__messages_get: {
        parameters: {
            query?: {
                limit?: number;
                before_ordinal?: number | null;
            };
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchMessagePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_api_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_history_api_search_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchHistory"][];
                };
            };
        };
    };
    delete_history_api_search_history__history_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                history_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_stream_api_search_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_api_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"][];
                };
            };
        };
    };
    create_tag_api_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tag_api_tags__tag_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tag_api_tags__tag_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workspaces_api_workspaces_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"][];
                };
            };
        };
    };
    create_workspace_api_workspaces_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_api_workspaces__workspace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_workspace_api_workspaces__workspace_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
