export const UI_COPY = {
  unknownError: "処理を完了できませんでした。もう一度お試しください",
  cancelled: "操作を中止しました。",
  ask: {
    cockpit: "研究対話",
    conversations: "研究対話",
    evidence: "最新回答の根拠",
    sources: "検索対象",
    sourceEmpty: "検索する論文を1〜5件選んでください。",
    sourceMaximum: "検索する論文は5件まで選べます。",
    timeout: "AIの回答が時間内に終わりませんでした。論文の抜粋が見つかった場合は、代わりに表示しています",
    retrySame: "同じ条件でもう一度",
  },
  discovery: {
    connectionHelp: "APIへ接続できませんでした。PaperPilot API が起動していることを確認して、もう一度検索してください。",
    retrySearch: "もう一度検索",
  },
  externalPaper: {
    loading: "論文情報を取得中…",
    success: "外部データベースから論文メタデータを登録しました。",
  },
} as const;

export const API_ERROR_COPY: Readonly<Record<string, string>> = {
  aborted: UI_COPY.cancelled,
  network_error: "通信できませんでした。接続を確認して、もう一度お試しください。",
  api_timeout: UI_COPY.ask.timeout,
  model_timeout: UI_COPY.ask.timeout,
  deadline_exceeded: UI_COPY.ask.timeout,
  incomplete_stream: "回答の受信が途中で止まりました。もう一度お試しください。",
  invalid_sse_json: "回答データを読み取れませんでした。もう一度お試しください。",
  invalid_sse_event: "回答データを読み取れませんでした。もう一度お試しください。",
  missing_response_body: "回答を受信できませんでした。もう一度お試しください。",
  stream_error: "回答を受信できませんでした。もう一度お試しください。",
  invalid_external_identifier: "DOI または arXiv ID の形式を確認してください。",
  external_paper_not_found: "外部データベースで論文情報が見つかりませんでした。DOI または arXiv ID を確認してください。",
  external_provider_rate_limited: "外部データベースの利用上限に達しました。少し時間をおいて、もう一度お試しください。",
  external_provider_unavailable: "外部データベースを一時的に利用できません。時間をおいて、もう一度お試しください。",
  invalid_provider_response: "外部データベースから有効な論文情報を取得できませんでした。DOI または arXiv ID を確認して、もう一度お試しください。",
  source_scope_required: "検索する論文を1〜5件選んでください。",
  source_scope_too_large: "検索する論文は5件まで選べます。",
  research_run_scope_mismatch: "検索する論文が変わりました。もう一度質問してください。",
  http_400: "入力内容を確認してください。",
  http_401: "ログインが必要です。もう一度ログインしてください。",
  http_403: "この研究プロジェクトで操作する権限がありません。",
  http_404: "対象のデータが見つかりませんでした。",
  http_409: "ほかの操作と重なりました。最新の状態を確認してください。",
  http_413: "データが大きすぎます。内容を減らして、もう一度お試しください。",
  http_422: "入力内容を確認してください。",
  http_429: "利用が集中しています。少し待ってから、もう一度お試しください。",
  http_500: "サービス側で問題が発生しました。時間をおいて、もう一度お試しください。",
  http_502: "サービスへ接続できませんでした。時間をおいて、もう一度お試しください。",
  http_503: "サービスを一時的に利用できません。時間をおいて、もう一度お試しください。",
  http_504: UI_COPY.ask.timeout,
};
